compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
      
yarnPath: .yarn/releases/yarn-4.5.1.cjs
