name: Check for Changeset

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  changeset:
    name: Changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Check for Changeset
        id: changeset
        run: |
          if git diff --name-only origin/main...HEAD | grep -q "^.changeset/.*.md$"; then
            echo "Changeset found."
          else
            echo "::error::No changeset found in this PR. Please add a changeset."
            exit 1
          fi
