name: Lock Changes

on:
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Lock Changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
        
      - name: Yarn Lock Changes
        uses: Simek/yarn-lock-changes@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
