name: Prepare Release

on: 
  push:
    branches:
      - test

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Sync Dependencies
        run: ./.ci/update-yarn-lock.sh
      