name: Release

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Check if changeset-release/main was merged
        id: check_merge
        run: |
          if git log -1 --oneline | grep -q 'changeset-release/main'; then
            echo "changeset-release branch was merged."
            echo "::set-output name=merged::true"
          else
            echo "changeset-release branch was not merged."
            echo "::set-output name=merged::false"
          fi

      - name: Sync Dependencies
        if: steps.check_merge.outputs.merged == 'true'
        run: ./.ci/update-yarn-lock.sh
        
      - name: Install Dependencies
        if: steps.check_merge.outputs.merged == 'false'
        run: yarn install

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          publish: yarn release
