name: Levana Packages

on: push

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install Dependencies
        run: yarn install

      - name: Code Quality
        run: yarn lint

