name: Levana Packages

on: push

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # - name: Set Node.js 16.x
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 
        with:
          cmd: install

      # - name: Install Dependencies
      #   run: yarn install

      # - name: Code Quality
      #   run: yarn lint

