name: Levana Packages

on: push

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # - name: Run local script to update yarn.lock
      #   run: ./.ci/update-yarn-lock.sh

      - name: Install Dependencies
        run: yarn install --mode update-lockfile

      # - name: Code Quality
      #   run: yarn lint

