name: Levana Packages

on:
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
        
      # - name: Install Dependencies
      #   run: ./.ci/update-yarn-lock.sh

      # - name: Install Dependencies
      #   run: yarn install --mode update-lockfile

      # - name: Code Quality
      #   run: yarn lint

      - name: Yarn Lock Changes
        uses: Simek/yarn-lock-changes@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
